# Generated by Django 5.1.2 on 2024-10-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("access", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_until", models.TextField()),
                ("time_after", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
