# Generated by Django 5.1.2 on 2024-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_users_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="access",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="users",
            name="time_after",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="users",
            name="time_until",
            field=models.DateField(),
        ),
    ]
