# Generated by Django 5.1.2 on 2024-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_users_access_alter_users_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code_activation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uid_card", models.CharField(max_length=50)),
                ("reg", models.IntegerField()),
                ("access_level", models.CharField(max_length=10)),
                ("user_name", models.CharField(max_length=100)),
                (
                    "departments",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "occupations",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.BigIntegerField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telegram", models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
