# Generated by Django 5.1.2 on 2024-11-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_user_delete_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("alien", "Alien"),
                    ("kent", "Kent"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
