# Generated by Django 5.1.2 on 2024-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_user_phone_number_alter_user_uid_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
