# Generated by Django 5.1.2 on 2024-11-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_user_phone_number_alter_user_telegram"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                ("car_plate_number", models.CharField(max_length=100)),
                ("brand_model", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("time_access", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "car_access",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("alien", "Alien"),
                    ("kent", "Kent"),
                ],
                default="user",
                max_length=20,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="code_activation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Код активации"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="departments",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Департамент"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Эл.почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="occupations",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid_card",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Код пропуска"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=100, verbose_name="Фио"),
        ),
    ]
