# Generated by Django 5.1.2 on 2024-11-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_cars_alter_user_access_level_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cars",
            new_name="Car_access",
        ),
    ]
