# Generated by Django 5.1.2 on 2024-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_cars_car_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(max_length=100, verbose_name="Уровень доступа"),
        ),
    ]
