# Generated by Django 5.1.2 on 2024-11-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_user_access_level"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="СustomUser",
        ),
    ]
