# Generated by Django 5.1.2 on 2025-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_сustomuser_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=26)),
                ('message', models.TextField(max_length=100)),
                ('auditory_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'logg',
            },
        ),
    ]
