# Generated by Django 5.1.2 on 2025-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_logg'),
    ]

    operations = [
        migrations.AddField(
            model_name='сustomuser',
            name='user_acesses',
            field=models.JSONField(blank=True, null=True, verbose_name='Доступы'),
        ),
    ]
