# Generated by Django 5.1.2 on 2025-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_сustomuser_user_acesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сustomuser',
            name='user_acesses',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Доступы'),
        ),
    ]
