# Generated by Django 5.1.2 on 2025-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_сustomuser_user_acesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id_device', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('device_activated', models.BooleanField(default=True)),
                ('mac', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('token', models.TextField()),
                ('tg_token', models.TextField(blank=True, null=True)),
                ('device_api', models.JSONField()),
                ('checkable', models.BooleanField(default=True)),
                ('calendar_regular', models.JSONField()),
                ('calendar_exception', models.JSONField(blank=True, null=True)),
                ('period', models.IntegerField(default=0)),
                ('device_status', models.CharField(blank=True, max_length=10, null=True)),
                ('trying_open', models.IntegerField(default=0)),
                ('trying_close', models.IntegerField(default=0)),
                ('trying_max', models.IntegerField(default=4)),
                ('trying_delay', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
