# Generated by Django 5.1.2 on 2025-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_api",
            field=models.JSONField(null=True),
        ),
    ]
