# Generated by Django 5.1.2 on 2025-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_device_device_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="calendar_regular",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
