# Generated by Django 5.1.2 on 2025-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_device_calendar_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_api',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
