# Generated by Django 5.1.2 on 2025-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_device_device_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_api',
            field=models.JSONField(null=True),
        ),
    ]
