# Generated by Django 5.1.2 on 2025-04-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_device_device_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id_device',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
