# Generated by Django 5.1.2 on 2025-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_device_id_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logg_parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=32)),
                ('id_user', models.CharField(max_length=32)),
                ('message', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'logg_parking',
            },
        ),
    ]
