# Generated by Django 5.1.2 on 2025-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_logg_parking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logg_access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.CharField(max_length=32)),
                ("uid_card", models.CharField(max_length=32)),
                ("action", models.TextField(max_length=100)),
                ("auditory_number", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "logg_access",
            },
        ),
    ]
