# Generated by Django 5.1.2 on 2025-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_logg_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditory",
            fields=[
                (
                    "auditory_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("key_free", models.IntegerField(default=0)),
                ("key_holder", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "verbose_name": "Аудитория",
                "verbose_name_plural": "Аудитории",
                "db_table": "auditory",
            },
        ),
        migrations.RenameField(
            model_name="logg_access",
            old_name="datetime",
            new_name="datetime",
        ),
    ]
