# Generated by Django 5.1.2 on 2025-05-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_logg_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logg_access',
            old_name='date_time',
            new_name='datetime',
        ),
    ]
