# Generated by Django 5.1.2 on 2025-05-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auditory_rename_date_time_logg_access_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditory',
            options={'managed': False, 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='car_access',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logg_access',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logg_parking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='сustomuser',
            options={'managed': False},
        ),
    ]
