# Generated by Django 5.1.2 on 2025-05-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_auditory_options_alter_car_access_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logg',
            options={},
        ),
    ]
