# Generated by Django 5.1.2 on 2025-05-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_logg_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_access',
            table='cars_access',
        ),
    ]
